### ISSUE TITLE
テストに利用するファイルが正常に取得できない

### ISSUE THREAD

**Issue by PyYoshi** [syoya/resizer#1]
## WHY

https://resizer.storage.googleapis.com/fixtures/

からテストに必要なファイルを取得を試みているがBucketが存在しないためXMLを取得してしまいテストが失敗する

## WHERE

https://github.com/syoya/resizer/blob/900e911c262e18df0e0f484f7d95b070dca11d6f/testutil/fixtures.go#L31-L35

https://github.com/syoya/resizer/blob/8c1455454d8e13f97a2ecdc774110cb1727e4943/processor/processor_test.go#L23-L38

**Comment by PyYoshi** [comment]
@keito-jp 手元にfixturesディレクトリと画像ファイル残ってます?

**Comment by keito-jp** [comment]
@PyYoshi 残ってないですね…
